Repository ManageIQ/manageiq-providers-embedded_terraform, pull requests merged in 2024-11, with the labels that each got.

#85 Ruby3.3
  .github/workflows/ci.yaml
Labels: test, ruby3.3

#71 Retire terraform runner stack
  app/models/manageiq/providers/embedded_terraform/automation_manager/job.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/template.rb
  app/models/service_template_terraform_template.rb
  app/models/service_terraform_template.rb
  lib/terraform/runner.rb
  lib/terraform/runner/response_async.rb
  spec/lib/terraform/runner/data/responses/hello-world-create-in-progress.json
  spec/lib/terraform/runner/data/responses/hello-world-delete-in-progress.json
  spec/lib/terraform/runner/data/responses/hello-world-delete-success.json
  spec/lib/terraform/runner/data/responses/hello-world-retrieve-create-success.json
  spec/lib/terraform/runner_spec.rb
  spec/models/manageiq/providers/embedded_terraform/automation_manager/job_spec.rb
  spec/models/manageiq/providers/embedded_terraform/automation_manager/stack_spec.rb
  spec/models/manageiq/providers/embedded_terraform/automation_manager/template_spec.rb
Labels: enhancement, radjabov/yes?

#86 Use terraform-runner /live api in Terraform::Runner.available? method
  lib/terraform/runner.rb
  spec/lib/terraform/runner_spec.rb
Labels: enhancement
