Repository ManageIQ/manageiq-providers-embedded_terraform, pull requests merged in 2024-05, with the labels that each got.

#2 Add Opentofu Worker
  app/models/opentofu_worker.rb
  app/models/opentofu_worker/runner.rb
  config/settings.yml
  systemd/opentofu-runner.service
  systemd/opentofu-runner.target
Labels: enhancement

#25 Move opentofu-runner container image name to an environment variable
  app/models/opentofu_worker.rb
  config/settings.yml
  systemd/opentofu-runner.service
Labels: enhancement

#26 Fix missing create_container_objects method in OpentofuRunner
  app/models/opentofu_worker.rb
Labels: bug

#24 Attaching volume to OpenTofu runner to read https certs
  app/models/opentofu_worker.rb
Labels: enhancement

#27 Fix OpentofuWorker worker_deployment_name
  app/models/opentofu_worker.rb
  spec/factories/miq_worker.rb
  spec/models/opentofu_worker_spec.rb
Labels: bug

#15 Add service_template_embedded_terraform_template
  app/models/manageiq/providers/embedded_terraform/automation_manager.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/job.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/stack.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/stack/status.rb
  app/models/service_template_terraform_template.rb
  app/models/service_terraform_template.rb
Labels: enhancement

#29 Override default containerport 3000 to opentofu runner port 6000
  app/models/opentofu_worker.rb
  spec/models/opentofu_worker_spec.rb
Labels: bug

#30 Fix Provision options for EmbeddedTerraform Stack
  app/models/manageiq/providers/embedded_terraform/automation_manager/stack.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/template.rb
  app/models/service_terraform_template.rb
Labels: bug, radjabov/yes?

#32 Fix missing Environment Variables in opentofu-runner
  systemd/opentofu-runner.service
Labels: bug, radjabov/yes?

#35 Fix MEMCACHE_SERVERS ENV var for opentofu-runner
  app/models/opentofu_worker.rb
  systemd/opentofu-runner.service
Labels: bug, radjabov/yes?

#33 Fix Terraform::Runner credentials
  app/models/manageiq/providers/embedded_terraform/automation_manager/job.rb
  lib/terraform/runner.rb
Labels: bug, radjabov/yes?

#41 Ensure the ccorrect port is exposed in kubernetes
  app/models/opentofu_worker.rb
  spec/models/opentofu_worker_spec.rb
Labels: bug, radjabov/yes?

#40 Fix opentofu-runner postgresql connection refused
  systemd/opentofu-runner.service
Labels: bug, radjabov/yes?

#42 Implement ServiceTerraformTemplate#refresh
  app/models/manageiq/providers/embedded_terraform/automation_manager/stack.rb
  app/models/service_terraform_template.rb
Labels: bug, radjabov/yes?

#46 Set the default port to 6000 since that's what is used in production
  lib/terraform/runner.rb
Labels: bug

#48 Fix handling of template_path with trailing `/`
  lib/terraform/runner.rb
  spec/lib/terraform/runner_spec.rb
Labels: bug, radjabov/yes
