Repository ManageIQ/manageiq-providers-embedded_terraform, pull requests merged in 2024-04, with the labels that each got.

#5 Sync Terraform Templates from git repo
  app/models/manageiq/providers/embedded_terraform/automation_manager/configuration_script_source.rb
  spec/factories/authentication.rb
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/embedded_terraform/automation_manager/configuration_script_source_spec.rb
  spec/support/fake_terraform_repo.rb
Labels: enhancement

#13 Add Embedded Terraform credential type
  app/models/manageiq/providers/embedded_terraform/automation_manager/credential.rb
Labels: enhancement

#7 Add methods to run Terraform Templates using TerraformRunner container APIs
  lib/terraform/runner.rb
  lib/terraform/runner/response.rb
  lib/terraform/runner/response_async.rb
  spec/lib/terraform/runner/data/hello-world/main.tf
  spec/lib/terraform/runner/data/responses/hello-world-create-success.json
  spec/lib/terraform/runner/data/responses/hello-world-retrieve-success.json
  spec/lib/terraform/runner_spec.rb
Labels: enhancement

#14 Use api/ping endpoint for the available? check
  lib/terraform/runner.rb
  spec/lib/terraform/runner_spec.rb
Labels: cleanup

#3 Add EmbeddedTerraform UI
  app/controllers/embedded_terraform_credential_controller.rb
  app/controllers/embedded_terraform_repository_controller.rb
  app/controllers/embedded_terraform_template_controller.rb
  app/helpers/application_helper/button/embedded_terraform.rb
  app/helpers/application_helper/toolbar/embedded_terraform_credential_center.rb
  app/helpers/application_helper/toolbar/embedded_terraform_credentials_center.rb
  app/helpers/application_helper/toolbar/embedded_terraform_repositories_center.rb
  app/helpers/application_helper/toolbar/embedded_terraform_repository_center.rb
  app/helpers/application_helper/toolbar/embedded_terraform_template_center.rb
  app/helpers/application_helper/toolbar/embedded_terraform_templates_center.rb
  app/helpers/embedded_terraform_credential_helper.rb
  app/helpers/embedded_terraform_credential_helper/textual_summary.rb
  app/helpers/embedded_terraform_repository_helper.rb
  app/helpers/embedded_terraform_repository_helper/textual_summary.rb
  app/helpers/embedded_terraform_template_helper.rb
  app/helpers/embedded_terraform_template_helper/textual_summary.rb
  app/views/embedded_terraform_credential/edit.html.haml
  app/views/embedded_terraform_credential/new.html.haml
  app/views/embedded_terraform_credential/show.html.haml
  app/views/embedded_terraform_credential/show_list.html.haml
  app/views/embedded_terraform_repository/_output.html.haml
  app/views/embedded_terraform_repository/edit.html.haml
  app/views/embedded_terraform_repository/new.html.haml
  app/views/embedded_terraform_repository/show.html.haml
  app/views/embedded_terraform_repository/show_list.html.haml
  app/views/embedded_terraform_template/map_credentials.html.haml
  app/views/embedded_terraform_template/show.html.haml
  app/views/embedded_terraform_template/show_list.html.haml
  config/routes.rb
  lib/manageiq/providers/embedded_terraform/engine.rb
  locale/en.yml
  product/views/ManageIQ_Providers_EmbeddedTerraform_AutomationManager_ConfigurationScriptSource.yaml
  product/views/ManageIQ_Providers_EmbeddedTerraform_AutomationManager_Credential.yaml
  product/views/ManageIQ_Providers_EmbeddedTerraform_AutomationManager_Template.yaml
Labels: enhancement

#17 Fix repository refresh button
  app/controllers/embedded_terraform_repository_controller.rb
Labels: bug

#12 Add EmbeddedTerraform Stack and Job
  app/models/manageiq/providers/embedded_terraform/automation_manager/job.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/stack.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/template.rb
  lib/terraform/runner/response_async.rb
  spec/factories/configuration_script_payload.rb
  spec/models/manageiq/providers/embedded_terraform/automation_manager/job_spec.rb
  spec/models/manageiq/providers/embedded_terraform/automation_manager/template_spec.rb
Labels: enhancement

#18 Add new table columns for templates and repositories
  product/views/ManageIQ_Providers_EmbeddedTerraform_AutomationManager_ConfigurationScriptSource.yaml
  product/views/ManageIQ_Providers_EmbeddedTerraform_AutomationManager_Template.yaml
Labels: enhancement

#16 Add cloud creds support for terraform runner
  app/models/manageiq/providers/embedded_terraform/automation_manager/amazon_credential.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/azure_credential.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/cloud_credential.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/credential.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/google_credential.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/ibm_cloud_credential.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/openstack_credential.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/vsphere_credential.rb
  lib/terraform/runner.rb
  lib/terraform/runner/amazon_credential.rb
  lib/terraform/runner/api_params.rb
  lib/terraform/runner/azure_credential.rb
  lib/terraform/runner/credential.rb
  lib/terraform/runner/generic_credential.rb
  lib/terraform/runner/google_credential.rb
  lib/terraform/runner/ibm_cloud_credential.rb
  lib/terraform/runner/openstack_credential.rb
  lib/terraform/runner/vsphere_credential.rb
  spec/factories/authentication.rb
  spec/lib/terraform/runner/amazon_credential_spec.rb
  spec/lib/terraform/runner/api_params_spec.rb
  spec/lib/terraform/runner/azure_credential_spec.rb
  spec/lib/terraform/runner/credential_spec.rb
  spec/lib/terraform/runner/generic_credential_spec.rb
  spec/lib/terraform/runner/google_credential_spec.rb
  spec/lib/terraform/runner/ibm_cloud_credential_spec.rb
  spec/lib/terraform/runner/openstack_credential_spec.rb
  spec/lib/terraform/runner/vsphere_credential_spec.rb
  spec/lib/terraform/runner_spec.rb
  spec/models/manageiq/providers/embedded_terraform/automation_manager/configuration_script_source_spec.rb
  spec/models/manageiq/providers/embedded_terraform/automation_manager/credential_spec.rb
  spec/support/embedded_terraform_evm_spec_helper.rb
Labels: enhancement
