Repository ManageIQ/manageiq-providers-embedded_terraform, pull requests merged in 2024-07, with the labels that each got.

#62 Adding environment variable for offline or airgap env
  app/models/opentofu_worker.rb
  config/settings.yml
Labels: enhancement

#63 Marshalling boolean value to environment varaible of type string
  app/models/opentofu_worker.rb
Labels: radjabov/yes?

#64 Fix credential type text
  locale/en.yml
Labels: bug

#66 Fix terraform template name
  app/models/manageiq/providers/embedded_terraform/automation_manager/configuration_script_source.rb
  spec/models/manageiq/providers/embedded_terraform/automation_manager/configuration_script_source_spec.rb
Labels: bug
