Repository ManageIQ/manageiq-providers-embedded_terraform, pull requests merged in 2024-06, with the labels that each got.

#54 Fix /home/node HOME directory
  app/models/opentofu_worker.rb
Labels: bug

#52 Fix some issues with opentofu-runner systemd service
  app/models/opentofu_worker.rb
  systemd/opentofu-runner.service
Labels: bug, radjabov/yes?

#53 Parse dialog options as Extra Vars
  app/models/manageiq/providers/embedded_terraform/automation_manager/job.rb
  app/models/service_terraform_template.rb
Labels: bug, radjabov/yes?

#56 Generate JWT token from v2_key
  bin/before_install
  lib/terraform/runner.rb
  manageiq-providers-embedded_terraform.gemspec
Labels: enhancement, radjabov/yes?

#55 Removed runAsUser from opentofu-runner deployment definition
  app/models/opentofu_worker.rb
Labels: bug, radjabov/yes

#57 Fix Failed ServiceTerraformTemplate Provision finishing with Success Status
  app/models/manageiq/providers/embedded_terraform/automation_manager/stack.rb
  app/models/manageiq/providers/embedded_terraform/automation_manager/stack/status.rb
  app/models/service_terraform_template.rb
  spec/factories/orchestration_stack.rb
  spec/factories/service.rb
  spec/models/manageiq/providers/embedded_terraform/automation_manager/stack_spec.rb
  spec/models/service_terraform_template_spec.rb
Labels: bug, radjabov/yes?

#58 Check embedded_terraform role in `Button::EmbeddedTerraform#disabled?`
  app/helpers/application_helper/button/embedded_terraform.rb
Labels: bug, radjabov/yes?
